apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
  labels:
    app: postgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
      - name: postgres-cont
        image: postgres:15.17-trixie
        ports:
        - containerPort: 5432
