apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pvc-demo-alert
  namespace: monitoring
  labels:
    release: monitor-stack-release
spec:
  groups:
  - name: pvc-demo.rules
    rules:
    - alert: PVCUsageHighDemo
      expr: (kubelet_volume_stats_used_bytes{namespace="default",persistentvolumeclaim="my-postgres-vol-postgres-demo-0"} /
            kubelet_volume_stats_capacity_bytes{namespace="default",persistentvolumeclaim="my-postgres-vol-postgres-demo-0"}) * 100 > 0.1
      for: 0s
      labels:
        severity: critical
      annotations:
        summary: "PVC usage above 0.1%"
        description: "PVC my-postgres-vol-postgres-demo-0 in default namespace usage exceeded 0.1%"