apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany
    # - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-demo
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /srv/nfs_shared/spring-images
    server: 10.148.0.2
