apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: pisethmao/itpmongodb:1.0.5
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: springboot-config