appName:
  app: nginx-stagging
replicas: 2
container:
  name: nginx-stagging-cont
  image: nginx:trixie-perl
  port: 80
  envs:
    - name: POSTGRES_USERNAME
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
    - name: POSTGRES_DB
      value: "postgres"
